
/*USUARIOS*/
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (100, TRUE, 'ADMIN', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'ADMIN', 'ADMIN@GMAIL.COM', TRUE, NULL);

INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (101, TRUE, 'JOSE MANUEL', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'BARGUEÑO', 'BARGUENO@GMAIL.COM', TRUE, NULL);
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (102, TRUE, 'JOSE MARIA', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'RUIZ', 'RUIZ@GMAIL.COM', TRUE, NULL);

INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (103, TRUE, 'DANIEL', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'TRONCOSO', 'TRONCOSO@GMAIL.COM', TRUE, NULL);
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (104, TRUE, 'JESUS', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'CEACERO', 'CEACERO@GMAIL.COM', TRUE, NULL);

INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (105, FALSE, 'PEDRO', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'HERRERA', 'HERRERA@GMAIL.COM', TRUE, NULL);
INSERT INTO APP_USER
    (ID, ADMIN, NAME, PASSWORD, SURNAME, USER_EMAIL, VALIDATED, SCHOOL_ID)
VALUES
    (106, FALSE, 'USER', '$2a$10$FPOPMxhJOxlqx4mGEmR8HOeCjAs3JwbRKhN2ypYwZMq4Ue1pNY4Vi', 'ADMIN', 'USER@GMAIL.COM', TRUE, NULL);

/*SCHOOL*/
INSERT INTO SCHOOL
    (ID, ADDRESS, NAME, SCHOOL_CODE)
VALUES
    (1, 'CONDE DE BUSTILLOS', 'SALESIANOS TRIANA', '0001-SALTRI');
/*
INSERT INTO SCHOOL
    (ID, ADDRESS, NAME, SCHOOL_CODE)
VALUES
    (2, 'GOLONDRINAS', 'PEDRO GARFIAS', '0002-PEDROGAR');
    */


/*TIME_ZONE*/


/*ROOM CATEGORY*/

INSERT INTO ROOM_CATEGORY
    (ID, CATEGORY_NAME)
VALUES(1000, 'INFORMÁTICA');

/*ROOM*/
INSERT INTO ROOM
    (ID, NAME, SCHOOL_ID, ROOM_CATEGORY_ID)
VALUES(1, 'AULA-1', 1, 1000);

/*RESERVED_DATE*/


/*RESERVECHECKER*/
INSERT INTO RESERVE_CHECKER
    (ID, WEEKEND_ON)
VALUES(1, FALSE);

